### ISSUE TITLE
CRON build broken after merging #230

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-persistence-jdbc#233]
(The issue may be unrelated to merging #230 )

The CRON build https://travis-ci.org/dnvriend/akka-persistence-jdbc/builds/536159790 failed both Java11 jobs with similar test failures on the `akka.persistence.jdbc.query.PostgresJournalSequenceActorTest` test.

**Comment by dwijnand** [comment]
No ideas.

**Comment by ennru** [comment]
I set up the scheduled build to run with Akka 2.6.0 
Let's see how it goes https://travis-ci.com/akka/akka-persistence-jdbc/builds

**Comment by ennru** [comment]
This is not a problem anymore.
