### ISSUE TITLE
Why deleted field is nullable?

### ISSUE THREAD

**Issue by feoktant** [akka/akka-persistence-jdbc#250]
In all schemas `journal.deleted` field is nullable, however, in Slick it is not:
[Postgres](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/test/resources/schema/postgres/postgres-schema.sql#L7):
```sql
CREATE TABLE IF NOT EXISTS public.journal (
----
  deleted BOOLEAN DEFAULT FALSE,
----
);
```

[In Slick:](https://github.com/dnvriend/akka-persistence-jdbc/blob/master/src/main/scala/akka/persistence/jdbc/journal/dao/JournalTables.scala#L36)
```scala
val deleted: Rep[Boolean] = column[Boolean](journalTableCfg.columnNames.deleted, O.Default(false))
```

Was it done intentionally, or should I create PR for that?

**Comment by WellingR** [comment]
As far as I know, this field should have a not null constraint. But you are right that it does not.

I think it should be possible to add this constraint without any problems

**Comment by patriknw** [comment]
Is that even used? I think the logical vs physical deletes is not supported in Akka Persistence API any more. All deletes are physical.

**Comment by WellingR** [comment]
If I am correct, there is a setting in akka-persistence-jdbc for logical/physical deletes. In addition when deleting all events, one must remain (with the deleted flag) so that the persistent actor will not re-use a previously used sequence number.

**Comment by feoktant** [comment]
> Is that even used? I think the logical vs physical deletes is not supported in Akka Persistence API any more. All deletes are physical.

It is used in code in several places.
