### ISSUE TITLE
Configure serialization to work with Akka 2.6

### ISSUE THREAD

**Issue by ennru** [akka/akka-persistence-jdbc#300]
### Short description

The tests fail on the scheduled build with Akka 2.6 as it tries to use Java serialization.

### Details

https://travis-ci.com/akka/akka-persistence-jdbc/jobs/266803245#L447

**Comment by patriknw** [comment]
Fix for JournalPerfSpec.Cmd is in PR https://github.com/akka/akka/pull/28333

**Comment by patriknw** [comment]
Until fixed the workaround is config `akka.actor.allow-java-serialization = on`

**Comment by ennru** [comment]
Solved with #305
