### ISSUE TITLE
New Journal Store Schema

### ISSUE THREAD

**Issue by octonato** [akka/akka-persistence-jdbc#315]
The new journal store table will have a few more fields: 

* `ser_id` (Int)
* `ser_manifest` (String)
* `event_manifest` (String)
* `event_payload` (String)
* `writer_uuid` (String)
* `timestamp` column (see [#28383](https://github.com/akka/akka/pull/28383)). Useful for metrics about read-side processors lagging. The timestamp will be addes as Long and defaulting to 0.

We need to refactor the Journal DAO for that new format.

The current table is called `journal`. Instead of altering it, we will design a new table structure and call it `journal_messages`. New users can just start using it from version 4.0.0 onward. Existing users will need to run the [migration procedure](https://github.com/akka/akka-persistence-jdbc/issues/317) to copy their data from `journal` to `journal_messages`. 

`ByteArrayJournalSerializer` should be moved to the [migration module](https://github.com/akka/akka-persistence-jdbc/issues/317) as we will need it for running migrations (reading old data from the `journal` table).

Next to the journal table, we need a `tags` table. There is a one-to-many relation between the two tables. One event can have zero or more tags.

The Journal DAO must take this into account and execute inserts on both tables atomically. 

Events by tag queries need to be refactored to consider the new `tags` table.

**Comment by patriknw** [comment]
maybe call it `journal_events` instead of `journal_messages`? Akka Persistence naming of these things as messages is wrong in my opinion, but we don't have to replicate that problem to more places than necessary.

**Comment by renatocaval** [comment]
Good. I confess that I was trying to align as much as possible. Cassandra calls it `message` while Couchbase is using `journal_message` in the singular.

**Comment by PerWiklander** [comment]
Aren't SQL tables typically named in the singular?

**Comment by xeppaka** [comment]
What is the purpose of event_manifest field?

**Comment by chbatey** [comment]
We also need to add columns for the metadata

**Comment by chbatey** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/467
