### ISSUE TITLE
New Snapshot Store Schema

### ISSUE THREAD

**Issue by octonato** [akka/akka-persistence-jdbc#316]
Like the journal store, the new snapshot will have a few more fields:

* `ser_id` (Int)
* `ser_manifest` (String)
* `snapshot_payload` (String)

We need to refactor the Snapshot DAO for that new format.

The current table is `snapshot`. Because we don't want destructive migrations, we can add a new schema table called `snapshots`. New users can just start using it from version 4.0.0 onward. Existing users will need to run the [migration procedure](https://github.com/akka/akka-persistence-jdbc/issues/317) to copy their data from `snapshot` to `snapshots`. 

`ByteArraySnapshotSerializer` should be moved to the [migration module](https://github.com/akka/akka-persistence-jdbc/issues/317) as we will need it for running migrations (reading old data from `snapshot` table).

**Comment by chbatey** [comment]
https://github.com/akka/akka-persistence-jdbc/pull/467
