### ISSUE TITLE
 Include timestamp in EventEnvelope

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-persistence-jdbc#337]
This was recently added in Akka and backported to 2.5.x series. 

The timestamp field was added to the `PersistentRepr` in a backwards-compatible fashion. That means we can upgrade to the Akka 2.5.29 and start using it. 

No new column is needed for it for the moment since we are serializing `PersistentRepr` and saving it as a blob. That said, it's perfectly possible to start to use the new timestamp field and pass it to the `EventEnvelope` when deserializing and delivering the event.

**Comment by patriknw** [comment]
That is right. Included in Protobuf serialization of PersistentRepr as optional field, and defaults to 0L if not assigned.

In the journal when writing we need to set the timestamp with `persistentRepr.withTimestamp(System.currentTimeMillis(())`

**Comment by renatocaval** [comment]
Resolved by #346
