### ISSUE TITLE
Release Akka Persistence JDBC 3.5.3

### ISSUE THREAD

**Issue by renatocaval** [akka/akka-persistence-jdbc#348]
### ~ 1 week before the release

- [x] Check that open PRs and issues assigned to the milestone are reasonable
- [x] Notify depending projects (Lagom) about the upcoming release
- [x] Create a new milestone for the [next version](https://github.com/akka/akka-persistence-jdbc/milestones)
- [x] Check [closed issues without a milestone](https://github.com/akka/akka-persistence-jdbc/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aclosed%20no%3Amilestone) and either assign them the 'upcoming' release milestone or `invalid/not release-bound`
- [ ] Close the [3.5.3 milestone](https://github.com/akka/akka-persistence-jdbc/milestones?direction=asc&sort=due_date)

### 1 day before the release

- [x] Make sure all important / big PRs have been merged by now
- [ ] Communicate that a new version is about to be released in [Gitter Akka Dev Channel](https://gitter.im/akka/dev)

### Preparing release notes in the documentation / announcement

- [ ] For non-patch releases: rename the 'akka-persistence-jdbc-x.x-stable' reporting projects in [WhiteSource](https://saas.whitesourcesoftware.com/Wss/WSS.html#!project;id=1706072) accordingly
- [ ] Review the [draft release notes](https://github.com/akka/akka-persistence-jdbc/releases)
- [ ] For non-patch releases: Create a news item draft PR on [akka.github.com](https://github.com/akka/akka.github.com), using the milestone

### Cutting the release

- [ ] Wait until [master build finished](https://travis-ci.com/akka/akka-persistence-jdbc/builds/) after merging the latest PR
- [ ] Update the [draft release](https://github.com/akka/akka-persistence-jdbc/releases) with the next tag version `v3.5.3`, title and release description linking to announcement and milestone
- [ ] Check that Travis CI release build has executed successfully (Travis will start a [CI build](https://travis-ci.com/akka/akka-persistence-jdbc/builds) for the new tag and publish artifacts to Bintray and documentation to Gustav)
- [ ] Go to [Bintray](https://bintray.com/akka/maven/akka-persistence-jdbc) and select the just released version
- [ ] Go to the Maven Central tab, check the *Close and release repository when done* checkbox and sync with Sonatype (using your Sonatype TOKEN key and password)

### Check availability

- [ ] Check [API](https://doc.akka.io/api/akka-persistence-jdbc/3.5.3/) documentation
- [ ] Check [reference](https://doc.akka.io/docs/akka-persistence-jdbc/3.5.3/) documentation
- [ ] Check the release on [Maven central](http://central.maven.org/maven2/com/lightbend/akka/akka-persistence-jdbc_2.12/3.5.3/)

### When everything is on maven central
  - [ ] Log into `gustav.akka.io` as `akkarepo` 
    - [ ] update the `current` links on `repo.akka.io` to point to the latest version with
         ```
         cd ~/www
         # MINORVERSION=4.0
         ln -nsf 3.5.3 docs/akka-persistence-jdbc/current
         ln -nsf 3.5.3 api/akka-persistence-jdbc/current
         ln -nsf 3.5.3 docs/akka-persistence-jdbc/$MINORVERSION
         ln -nsf 3.5.3 api/akka-persistence-jdbc/$MINORVERSION
         ```
    - [ ] check changes and commit the new version to the local git repository
         ```
         cd ~/www
         git status
         git add docs/akka-persistence-jdbc/$MINORVERSION docs/akka-persistence-jdbc/current docs/akka-persistence-jdbc/3.5.3
         git add api/akka-persistence-jdbc/$MINORVERSION api/akka-persistence-jdbc/current api/akka-persistence-jdbc/3.5.3
         git commit -m "Akka Persistence JDBC 3.5.3"
         ```

### Announcements

- [ ] For non-patch releases: Merge draft news item for [akka.io](https://github.com/akka/akka.github.com)
- [ ] Send a release notification to [Lightbend discuss](https://discuss.akka.io)
- [ ] Tweet using the [@akkateam](https://twitter.com/akkateam/) account (or ask someone to) about the new release
- [ ] Announce on [Gitter akka/akka](https://gitter.im/akka/akka)
- [ ] Announce internally (with links to Tweet, blog, discuss)

### Afterwards

- [ ] Update version for [Lightbend Supported Modules](https://developer.lightbend.com/docs/lightbend-platform/introduction/getting-help/build-dependencies.html) in [private project](https://github.com/lightbend/lightbend-platform-docs/blob/master/docs/modules/getting-help/examples/build.sbt)
- Close this issue

**Comment by renatocaval** [comment]
@WellingR, we are good to release v3.5.3. Could you publish it for us? 

Don't worry about all the TODOs on this page. I will do the necessary steps.

**Comment by WellingR** [comment]
I published the artifacts to bintray, and tagged the git repo. I sent an email to Dennis to ask him to trigger a sync
