### ISSUE TITLE
Failed: sbt launcher is unable to detect the Scala version

### ISSUE THREAD

**Issue by ignasi35** [akka/akka-persistence-jdbc#384]
```
The command "${PRE_CMD:=return 0}" exited with 0.
2.49s$ sbt -jvm-opts .jvmopts-travis "$CMD"
Picked up _JAVA_OPTIONS: -XX:+UnlockExperimentalVMOptions -XX:+UseJVMCICompiler
[error] [launcher] error during sbt launcher: sbt/sbt#4955!
[error] [launcher] sbt launcher is unable to detect the Scala version for org.scala-sbt:sbt;
[error] [launcher] this likely indicates an incomplete artifact resolution and/or corrupt boot cache (~/.sbt/boot/).
[error] [launcher] the following is the full classpath that was retrieved for org.scala-sbt:sbt:
[error] [launcher]  * /home/travis/.sbt/boot/other/org.scala-sbt/sbt/1.3.9/sbt-1.3.9.jar
The command "sbt -jvm-opts .jvmopts-travis "$CMD"" exited with 1.
before_cache.1
0.01s$ find $HOME/.ivy2 -name "ivydata-*.properties" -delete
before_cache.2
0.01s$ find $HOME/.sbt -name "*.lock" -delete
cache.2
store build cache
```

This appeared in two different PR's at once ([this](https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/318268533) and [this](https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/318098408)). It points to https://github.com/sbt/sbt/issues/4955.

I tried a workaround in https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/318098408: clean the cache and restart the job. The failure persists.

What's weird, though, is that both failed jobs ([this](https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/318268533) and [this](https://travis-ci.com/github/akka/akka-persistence-jdbc/jobs/318098408)) are the exact same job (`Run tests with Scala 2.13 and AdoptOpenJDK 11`) but for different builds. I mean, I see how running `sbt` on JDK11 could have a regression, but I find it weird, this only manifests in JDK11 _and_ scala2.13.

**Comment by renatocaval** [comment]
It seems that this was fixed in sbt v1.3.10. Since it was merged all other PRs passed. 

They are all merged now.
