### ISSUE TITLE
Slow quering the highest sequence number in the journal table on Oracle DB

### ISSUE THREAD

**Issue by samfrown** [akka/akka-persistence-jdbc#400]
### Versions used

akka-persistence-jdbc: 3.5.0
slick: 3.3.2

Akka version: 2.5.23

### Expected Behavior

Predictable time for an actor persistent state loading on restart from Oracle DB in production.

### Actual Behavior

We are using akka-persistence to store state in Oracle Database.

Our average load is about 80M events per day.

We don't use hard deletion of events as it greatly increase database load. Instead we use database side job which clean up data by dropping outdated table partition daily.
The "journal" table is partitioned by "creation_time" column and we could safely drop a previous day partition after the first current day snapshot is saved.

So, lately we faced a problem of very slow journal loading when the actor was restarted at the end of a day.

During investigation we found that most time during loading actor spent in the following query:

```
select x2.x3 from (select "sequence_number" as x3 from "journal"
where "persistence_id" = :1 order by "sequence_number" desc) x2
where rownum <= 1
```

Caused by the nested query with the "order by ... desc" statement this query tends to have a non-optimal execution plan for the table with significant amount of records.

In our production environment we measured up to 10 minutes execution time for it.

To fix this issue we changed a query code in [JournalQueries.scala](https://github.com/akka/akka-persistence-jdbc/compare/3.5.x...samfrown:optimize_query_of_highest_seq_number) which produce an sql like this:
```
select max("sequence_number") from "journal" where "persistence_id" = :1
```

This query has simplier execution plan and has more constant evaluation time regardless of the size on the table.

### Relevant logs

n/a

### Reproducible Test Case

Oracle Database 12c
Number of events: 80 000 000
Size of the event: 100 bytes

**Comment by WellingR** [comment]
I had a quick and these changes make sense. Could you create pull request for this?

**Comment by octonato** [comment]
Done in #401
