### ISSUE TITLE
Is there a good way to do double publish of the event log for hot-hot availability use cases?

### ISSUE THREAD

**Issue by alexmnyc** [akka/akka-persistence-jdbc#409]
Is there a good way to do double publish of the event log for hot-hot availability use cases?

**Comment by renatocaval** [comment]
I'm not sure I do understand your request. Can you elaborate?

**Comment by alexmnyc** [comment]
I would like the journal to be double published to two different regions for a hot-hot setup. So, that in case of failure in region A, region B would contain the exactly same event log and an Actor could be restarted from region B if needed

**Comment by alexmnyc** [comment]
I see this https://doc.akka.io/docs/akka-enhancements/current/persistence-dc/index.html

But it looks to be a commercial feature

**Comment by patriknw** [comment]
It will be open sourced soon. https://www.lightbend.com/blog/lightbend-to-contribute-commercial-features-to-akka-open-source

**Comment by renatocaval** [comment]
@alexmnyc thanks for the details. As Patrik mention, we will be open sourcing it, but it. However, the JDBC plugin is not yet ready to make use of it. We will need some extra work on this plugin to make it happen. 

It will take a while, but stay tuned...

**Comment by ennru** [comment]
The new database schema introduced in release 5.0.0 allows using Akka Persistence JDBC with [Replicated Event Sourcing](https://doc.akka.io/docs/akka/current/typed/replicated-eventsourcing.html).
