### ISSUE TITLE
Add metadata for Replicated Event Sourcing

### ISSUE THREAD

**Issue by patriknw** [akka/akka-persistence-jdbc#431]
It already works for events since the full PersistentRepr is serialized.

New columns are needed for metadata in the snapshots.

Corresponding Cassandra PR https://github.com/akka/akka-persistence-cassandra/pull/811 and Spanner PR https://github.com/akka/akka-persistence-spanner/pull/95

cc @johanandren @chbatey

**Comment by chbatey** [comment]
Done as part of https://github.com/akka/akka-persistence-jdbc/issues/315
