### ISSUE TITLE
Missing breaking documentation for 4.X to 5.X migration ?

### ISSUE THREAD

**Issue by rdubois** [akka/akka-persistence-jdbc#504]
### Versions used 

Akka version: 2.6.12

### Expected Behavior

The migration documentation is about changing the DAOs to be used when using old schemas. I think there is a missing part in the documentation related to `JdbcAsyncWriteJournal` which relies on `Legacy` table configuration to create the journal config.

Before the change, the `JdbcAsyncWriteJournal` did use that kind of config:

```
jdbc-journal {
  class = "akka.persistence.jdbc.journal.JdbcAsyncWriteJournal"

  tables {
    journal {
     tableName = "journal"
     schemaName = ""
   }
  }
}
```

It seems it now must be changed to:

```
jdbc-journal {
  class = "akka.persistence.jdbc.journal.JdbcAsyncWriteJournal"

  tables {
    legacy_journal {
     tableName = "journal"
     schemaName = ""
   }
  }
}
```

And this is the same for the snapshot table.

Did I miss anything ?

### Actual Behavior

N/A

### Relevant logs

N/A

### Reproducible Test Case

N/A

**Comment by octonato** [comment]
@rdubois, you are right. The config moved to `legacy_journal`. Same for the snapshot.

Thanks for reporting it.

**Comment by rdubois** [comment]
Documentation has been updated. I clode that issue.
