### ISSUE TITLE
Cannot extend slick.jdbc.OracleProfile with akka-persistence-jdbc

### ISSUE THREAD

**Issue by skisel** [akka/akka-persistence-jdbc#521]
### Versions used 

akka-persistence-jdbc: 5.0.0
Akka version: 2.6.12

### Expected Behavior

It should be possible to persist big messages (>4000 bytes) if custom profile is used (still extends slick.jdbc.OracleProfile)

### Actual Behavior

Oracle fails to persist messages with: `ORA-01461: can bind a LONG value only for insert into a LONG column`

**Comment by octonato** [comment]
Done in #522
