### ISSUE TITLE
CI releases snapshot on release

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-jdbc#542]
While releasing 5.0.1 publishing the draft, tagging the v-tag ended up with the release CI job publishing a -SNAPSHOT version. I had to delete the tag and re-tag it to get the actual -5.0.1 version on artifacts and docs.

**Comment by ennru** [comment]
This was before publishing switched to the Akka repo. I assume it was solved as the current setup uses `isSnapshot`.
