### ISSUE TITLE
Deserialize with event adapter manifest (if available) 

### ISSUE THREAD

**Issue by pawelkaczor** [akka/akka-persistence-jdbc#630]
### Short description

Serialization manifest that is produced by akka.persistence.typed.EventAdapter then passed to PersistentRepr.manifest and stored in JournalAkkaSerializationRow.adapterManifest is not used in deserialization.

### Details

I'm using the following event adapter (akka.persistence.typed.EventAdapter):

```scala
class EventEnvelopeAdapter extends EventAdapter[MyEvent, MyEventEnvelope] {
  override def toJournal(event: MyEvent): MyEventEnvelope =
    MyEventEnvelope(event, entityId(event), domain, userContextProvider.tenant)

  override def fromJournal(p: EventEnvelope, manifest: String): EventSeq[ControlEvent] =
    EventSeq.many(convert(EntityAccessRegistered(p.entityId, p.domain, p.tenant)), p.event)

  override def manifest(event: MyEvent): String =
    eventManifestMap(event.getClass) // returns subtype name as configured in Jackson
}
```

MyEventEnvelope gets stored in the journal with "MyEventEnvelope" in the event_ser_manifest column and actual event subtype name gets stored in the adapter_manifest column (mysql).
I found out that akka.persistence.PersistentRepr (that is passed to the journal plugin) contains actual event subtype (manifest produced by the event adapter) in manifest field .

Unfortunately, adapter manifest is ignored in the deserialization logic (https://github.com/akka/akka-persistence-jdbc/blob/43282e545c9cd77b47decd955ec7c43c68f641e0/core/src/main/scala/akka/persistence/jdbc/AkkaSerialization.scala#L33).

As the consequence, I won't be able to run JacksonMigrations for my events :-(

**Comment by pawelkaczor** [comment]
@patriknw I asked a question before submitting the issue: https://github.com/akka/akka-persistence-jdbc/commit/0d2f1eef912d823b9edd04c421c76acc19214f33#r62178142

As I understand my problem can not be solved here and I should close the issue?

**Comment by patriknw** [comment]
No problem. If you agree with my description you can close the issue, thanks.
