### ISSUE TITLE
Failed: CurrentEventsByTagTest

### ISSUE THREAD

**Issue by Roiocam** [akka/akka-persistence-jdbc#782]
lntegration Tests flaky after PR #731, i will investigate why and fix it.

**Failure Job**
- https://github.com/akka/akka-persistence-jdbc/actions/runs/6666883645/job/18119286722
- https://github.com/akka/akka-persistence-jdbc/actions/runs/6666879997/job/18119279713
- https://github.com/akka/akka-persistence-jdbc/actions/runs/6666880004/job/18119279323

They both point to the flaky occurring in CurrentEventsByTagTest.

**Comment by ennru** [comment]
Hopefully fixed by
- #783
