### ISSUE TITLE
SQL server CI tests no longer working

### ISSUE THREAD

**Issue by johanandren** [akka/akka-persistence-jdbc#860]
When trying to run the docker image topaztechnology/mssql-server-linux the container becomes stuck in a restart loop. Can be repeated locally without running any test, just starting the docker image.

Crash loop log from container:
[crashlooplog.txt](https://github.com/user-attachments/files/17077326/crashlooplog.txt)

**Comment by johanandren** [comment]
I'm guessing something date related since we have not merged any changes around SQL Server for a long while and this just started failing recently.

**Comment by ennru** [comment]
Fixed with
- #863
